FileNotFoundError in line 3 of /mnt/data/bind_homes/chris/hrdetect-pipeline/projects/pog.smk:
[Errno 2] No such file or directory: 'config/pog_custom_cohorts.tsv'
  File "/mnt/data/bind_homes/chris/hrdetect-pipeline/Snakefile", line 26, in <module>
  File "/mnt/data/bind_homes/chris/hrdetect-pipeline/projects/pog.smk", line 3, in <module>
  File "/home/chris/conda/envs/dependencies/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
  File "/home/chris/conda/envs/dependencies/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
  File "/home/chris/conda/envs/dependencies/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
  File "/home/chris/conda/envs/dependencies/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
  File "/home/chris/conda/envs/dependencies/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
